version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/local/django/Dockerfile
    command: >
      sh -c "python manage.py migrate --no-input &&
             python manage.py collectstatic --no-input &&
             python manage.py runserver 0.0.0.0:8000"

    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
#    ports:
#      - '8000:8000'
    env_file:
      - .env
#    depends_on:
#      - postgres-db
    #restart: 'on-failure'
    networks:
      - 'backend-django'

#  postgres-db:
#    image: postgres:14-alpine
#    ports:
#      - '5432:5432'
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#    networks:
#      - 'backend-django'

  web:
    restart: always
    depends_on:
      - api
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - 'backend-django'

networks:
  backend-django:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:

