# Generated by Django 4.0.3 on 2022-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=2)),
            ],
        ),
    ]
